# Generated by Django 4.2.3 on 2023-07-14 05:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KwakGV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytext',
            name='board_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
