# Generated by Django 4.2.3 on 2023-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwakGV', '0003_mytext_category_alter_mytext_board_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytext',
            name='category',
        ),
        migrations.AddField(
            model_name='mytext',
            name='actor',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='mytext',
            name='director',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='mytext',
            name='running_time',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
    ]
