# Generated by Django 4.1.6 on 2023-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytext',
            name='contents',
        ),
        migrations.AddField(
            model_name='mytext',
            name='genre',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='mytext',
            name='star_rate',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='mytext',
            name='year',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
