# Generated by Django 4.2.3 on 2023-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_myidea_liked_by_myidea_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydev',
            name='ideas',
            field=models.ManyToManyField(blank=True, related_name='devtools', to='posts.myidea', verbose_name='관련 아이디어'),
        ),
    ]
