# Generated by Django 4.2.3 on 2023-07-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_mydev_ideas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydev',
            name='ideas',
        ),
    ]
